spring.application.name: api-gateway
server.port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter: DEBUG
    org.springframework.data.redis.connection: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: employee_service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees
            - Method=GET,POST
          filters:
            - RewritePath=/api/employees, /employees
        - id: employee_fetch_service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
            - Method=GET
          filters:
            - RewritePath=/api/employees/(?<remaining>.*), /employees/${remaining}
            - name: AuthFilter
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2
#                key-resolver: "#{@userKeyResolver}"

        - id: department_service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments
            - Method=GET,POST
          filters:
            - RewritePath=/api/departments, /departments
        - id: departments_fetch_service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
            - Method=GET
          filters:
            - RewritePath=/api/departments/(?<remaining>.*), /departments/${remaining}