spring.application.name: api-gateway
server.port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter: DEBUG
    org.springframework.data.redis.connection: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: employee_service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees
            - Method=GET,POST
          filters:
            - RewritePath=/api/employees, /employees
            - name: AuthFilter
            - name: MonetizationFilter
        - id: employee_fetch_service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
            - Method=GET
          filters:
            - RewritePath=/api/employees/(?<remaining>.*), /employees/${remaining}
            - name: AuthFilter
            - name: MonetizationFilter

        - id: department_service
          uri: lb://department_service
          predicates:
            - Path=/api/departments
            - Method=GET,POST
          filters:
            - RewritePath=/api/departments, /departments
            - name: AuthFilter
            - name: MonetizationFilter
        - id: departments_fetch_service
          uri: lb://department_service
          predicates:
            - Path=/api/departments/**
            - Method=GET
          filters:
            - RewritePath=/api/departments/(?<remaining>.*), /departments/${remaining}
            - name: AuthFilter
            - name: MonetizationFilter